# Site settings
sparkversion: 2.8.0
templateversion: 2.7.1
description: > # > means to ignore newlines as long as indent is kept
  unirest-java
  Unirest in Java: Simplified, lightweight HTTP client library.
baseurl: "/unirest-java" # the subpath of your site, e.g. /blog
url: "http://kong.github.io" # the base hostname & protocol for your site
gems: [jekyll-redirect-from]

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
